- models/event.go
- models/event_test.go
There are more and more requirements that needs to tag a json object
instead of json string into the event.  PMY bus scenario is one among
these requirements.  This commit updates the event struct from
map[string]string tag to map[string]interface{}.
Signed-off-by: Jude Hung <jude@iotechsys.com>
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/.github/Contributing.md.
Are there any specific instructions or things that should be known prior to reviewing?
> PS-166 Upate event tags from map[string]string to map[string]interface{}

- dtos/address.go
- dtos/address_test.go
> Adding the PATCH method to Address DTO validate tag
Pick the community changes to this repo. 
https://github.com/edgexfoundry/go-mod-core-contracts/pull/686
> fix: Adding the missed PATCH method in REST Address DTO

- dtos/deviceprofile.go
- dtos/deviceprofile_test.go
- dtos/requests/deviceprofile_test.go
- models/deviceprofile.go
- v1models/transform.go
- v1models/transform_test.go
XRT will support v2 profile, but it needs `apiVersion` fieldhttps://iotechsys.atlassian.net/wiki/spaces/EN/pages/3081306123/XRT+V2+SDK+Device+Service+Update+Tips
We should add to DTO and model, and will use in xrt-bridge
> EDX-2347 Add apiVersion in Device Profile for Xpert

- dtos/device.go
- dtos/requests/device_test.go
GUI always assumes protocolName is lowerCase, so we should handle the case sensitive issue before storing to the database
> EDX-2385 Convert protocolName to lowerCase when transferring to model

- xrtmodels/response.go
Add Error field for the XRT error response.
The error response format might be:
{"client":"...","error":"...","request_id":"...","result":{"success":false},"success":false}
or {"client":"...","request_id":"...","result":{"error":"...","success":false}}
> EDX-2580 Improve the XRT error message

- v1models/transform.go
- v1models/transform_test.go
v1 to v2 model transform should convert the StartingAddress from string to int
> DCT-532 v1 to v2 model transform should convert StartingAddress

- common/constants.go
- dtos/devicecommand.go
- dtos/deviceprofile.go
- dtos/requests/deviceprofile_test.go
- dtos/resourceproperties.go
Cherry pick from community [commit](https://github.com/edgexfoundry/go-mod-core-contracts/commit/b3917be5ab0aa2c013b1cae3b52349178916ea57).
fix: Update the ReadWrite validation to include WR
Update the ReadWrite validation to include 'WR' value.
> EDX-2632 cherry pick - Update the ReadWrite validation to include WR

- dtos/deviceresource.go
[Issue link](https://iotechsys.atlassian.net/browse/EDX-2700)
Add omitempty attribute to tag field of DeviceResource dto.
> EDX-2700 Add omitempty to tag of DeviceResource dto

- common/validator.go
Allow Semicolon and Equal sign as unreserved characters for XRT v2
> EDX-2653 Allow Semicolon and Equal sign as unreserved characters

- dtos/reading.go
The SimpleReading can contain the empty string.
> EDX-2727 Remove JSON omitempty from SimpleReading value

- common/tls.go
This constant is required by edgex-go-private and xrt-xpert-bridge.
> EDX-2690-2 Add constant EnvMessageBusMqttTls

- dtos/provisionwatcher.go
- dtos/provisionwatcher_test.go
- dtos/requests/provisionwatcher.go
- dtos/requests/provisionwatcher_test.go
- models/provisionwatcher.go
Add ProtocolName to ProvisionWatcher for auto-discovered devices.
> EDX-2807 Add ProtocolName to ProvisionWatcher

- clients/http/notification.go
- clients/http/notification_test.go
- clients/interfaces/notification.go
- common/constants.go
Added methods:
- NotificationsByQueryConditions
- DeleteNotificationByIds
- UpdateNotificationAckStatusByIds
Also added parameter `ack` to the following methods:
- NotificationsByCategory
- NotificationsByLabel
- NotificationsByStatus
- NotificationsByTimeRange
- NotificationsBySubscriptionName
For further information on the Notification Service API changes, refer to: https://github.com/IOTechSystems/edgex-go-private/commit/3ba5e37ab791cde84693040f650503db57d718df
> PS-373 Add new methods for NotificationClient

- dtos/address.go
When mqtt-broker is enabled with TLS connection, scheme needs to be
"tcps" instead of default "tcp".  Add scheme as part of
NewMQTTAddressWithSecurity signature, so that a MQTT Address can be
specified with scheme during creation.
Signed-off-by: Jude Hung <jude@iotechsys.com>
> EDX-3040 Add scheme as part of NewMQTTAddressWithSecurity signature

- common/dummy_validator.go
- common/validator.go
DCT still uses go 1.16, so it needs `// +build` comment(`//go:build` comment for go 1.17+)
> EDX-3024 Add // +build comment for go 1.16 for DCT

- common/validator.go
- dtos/requests/const_test.go
> EDX-3111 Allow dot and asterisk char in the name field

- clients/http/utils/common.go
- clients/http/utils/request.go
If failed to json unmarshal, return the response error instead of the json format error.
> EDX-3131 Handle Client API error response

- common/validator.go
- dtos/provisionwatcher.go
When using the String pointer in the DTO, the validation tag omits the nil value and checks empty String with reserved chars. To preventing checking error, add len=0 to allow empty string for updating the profileName, deviceNameTemplate, profileNameTemplate, protocolName.
> EDX-3281 Allow using empty string to update ProvisionWatcher

- clients/http/kvs.go
- clients/http/kvs_test.go
- clients/http/utils/request.go
- clients/interfaces/kvs.go
- common/constants.go
- dtos/requests/kvs.go
- dtos/requests/kvs_test.go
- dtos/responses/kvs.go
- dtos/responses/kvs_test.go
- models/kvs.go
Implement the KVS http client for Keeper which invokes the /kvs APIs.
> EDX-3537 Implement the KVS http client for Keeper

- common/validator.go
- dtos/autoevent.go
- dtos/interval.go
Add min/max params for edgex-dto-duration tag to define the allowed duration range, to define the allowed min scheduler/autoevent interval.
_The fix in Xpert is differnet from the one in https://github.com/edgexfoundry/edgex-go/issues/4586 which only adds warning logs when the interval is less than the minimum values._
> EDX-3997 Add min/max params for edgex-dto-duration tag

- clients/http/registry.go
- clients/http/registry_test.go
- clients/interfaces/registry.go
- common/constants.go
- dtos/registration.go
- dtos/registration_test.go
- dtos/requests/registration.go
- dtos/requests/registration_test.go
- dtos/responses/registration.go
- dtos/responses/registration_test.go
- models/registration.go
Add http clients/dtos for Keeper.
> EDX-4229 Add http clients/dtos for Keeper registry

- dtos/requests/operation.go
- dtos/requests/operation_test.go
Add UseRegistry field to identify whether app service should be started with --registry flag.
> EDX-4242 Add UseRegistry field to OperationRequest DTO

- dtos/registration.go
- models/consts.go
Add HALT health status constant for Keeper and validation check.
> EDX-4301 Add HALT status constant for Keeper

- clients/http/registry.go
- clients/http/registry_test.go
- clients/interfaces/registry.go
- common/constants.go
Add deregistered param to allRegistry http client.
> EDX-4301 Add deregistered param to allRegistry

- clients/http/utils/common.go
If the error response is not JSON format, wrap the error code and error message properly.
> EDX-4285 Handle none JSON Http request error properly

- central/dbc/constants.go
- central/dbc/transform.go
- central/dbc/transform_test.go
The library removed the Extended Flag from the CAN ID. We need to add it back to ensure that the CAN ID remains consistent with the DBC file.
> PS-547-3 Use original CAN ID in DBC translation

- central/xlsx/device.go
- central/xlsx/deviceprofile.go
- central/xlsx/interface.go
- central/xlsx/mapping.go
- central/xlsx/reader.go
- central/xlsx/transform.go
- central/xlsx/utils.go
Improve error message for parsing xlsx row to include column header name.
> EDX-4443 Improve error message for parsing xlsx row

- central/xlsx/deviceprofile.go
- central/xlsx/deviceprofile_test.go
Allow no data row defined on the DeviceCommand sheet without returing error.
> EDX-4491 Allow no data row defined on the DeviceCommand sheet

- central/xlsx/reader.go
Check the cell header belongs to attribute field from MappingTable before converting to DeviceResource.
> EDX-4494 Check the cell header belongs to attr field

- xrtmodels/request.go
Assign a uuid to device profile name for NewDeviceScanRequest if empty.
> EDX-4517 Assign deviceprofile name for NewDeviceScanRequest

- central/xlsx/deviceprofile.go
Filter out empty column for xlsx DeviceCmd conversion. Only convert non-empty column.
> EDX-4537 Filter out empty column for DeviceCmd

- common/central_constants.go
- v2models/autoevent.go
- v2models/device.go
- xrtmodels/deviceInfo.go
Add "IOTech_" prefix to all the first level Device properties we use.
- Add "IOTech_" prefix constant
- Add v2 device model
> EDX-4649 Add "IOTech_" prefix constant

- common/central_constants.go
- dtos/provisionwatcher.go
- dtos/provisionwatcher_test.go
- dtos/requests/provisionwatcher.go
- dtos/requests/provisionwatcher_test.go
- models/central.go
- models/provisionwatcher.go
Move all the customized ProvisionWatcher fields to properties field
- Also add “IOTech_” prefix to the first level of properties
- Rename all the “NameTemplate” to “NamePattern”
> EDX-4650 Move customized ProvisionWatcher fields to properties

- clients/http/utils/central.go
- common/validator.go
- dtos/deviceprofile.go
- dtos/deviceservice.go
- dtos/reading_test.go
- dtos/requests/provisionwatcher_test.go
- models/deviceresource.go
- xrtmodels/deviceInfo.go
> EDX-4721 Remove unused variables and function to fix lint

- dtos/event_test.go
- xrtmodels/deviceInfo.go
- xrtmodels/xrtconv.go
- xrtmodels/xrtconv_test.go
Since the protocol properties support the interface in v3, we can remove the data type conversion of xrt protocol properties.
> EDX-4786 Remove xrt protocol properties dataType conversion

- central/xlsx/reader.go
- central/xlsx/reader_test.go
Remove the header cell leading/trailing spaces of xlsx import.
> EDX-4855 Remove the header cell spaces of xlsx import

- central/xlsx/constants.go
- central/xlsx/device_test.go
- central/xlsx/reader.go
- central/xlsx/reader_test.go
Support multi-level/nested protocolProperties device xlsx conversion.
> EDX-4908 Support multi-level prtProp device xlsx conversion

- central/xlsx/constants.go
- central/xlsx/dpXlsxWriter.go
- central/xlsx/dpXlsxWriter_test.go
- central/xlsx/transform_test.go
Add more resource property fields to be converted from DTO to xlsx file.
> EDX-4993 Add more resource property fields to be converted

- central/dtos/transform.go
- central/dtos/transform_test.go
Add the transform v2 DeviceProfile DTO to v3 function.
> GUIT-1079 Add transform v2 DeviceProfile DTO to v3 func

- common/central_constants.go
- common/constants.go
- common/validator.go
- dtos/reading.go
- dtos/reading_test.go
- models/reading.go
Leverage the object reading for ObjectArray valueType
> feat: Add ObjectArray valueType support (#899)

- xrtmodels/response.go
Update MultiComponentsResponse xrt model to re-use ComponentsDiscoveryResponse instead.
> EDX-4606 Update MultiComponentsResponse xrt model

- clients/http/utils/request.go
Not unmarshal to returnValuePointer if no response returned from http request.
> EDX-5171 Fix the error when no response in DeleteRequest http func

- central/dtos/transform.go
- central/dtos/transform_test.go
Fix the v2 to v3 Res Property transform error of the pointer fields.
> GUIT-1135 Fix the v2 to v3 Res Property transform error

- .golangci.yml
- dtos/event_test.go
- dtos/reading.go
- dtos/reading_test.go
- dtos/requests/event.go
- dtos/requests/event_test.go
Allow reading value to be null
closes: #931
(cherry picked from commit 4a7a10a3a61d76941da71588a5da288692112b8f)
> feat: Allow reading value to be null

- dtos/deviceprofilebasicinfo.go
Add omitempty to json annotation Id field of DeviceProfileBasicInfo DTO.
> GUIT-1159 Add omitempty to DeviceProfileBasicInfo Id field

- common/validator.go
- dtos/requests/user.go
- dtos/requests/user_test.go
- dtos/responses/user.go
- dtos/responses/user_test.go
- dtos/user.go
- dtos/user_test.go
- models/user.go
Add the user DTO/model for proxy-auth APIs.
> EDX-5338 Add the user DTO/model

- dtos/autoevent.go
- dtos/requests/device_test.go
- dtos/requests/provisionwatcher_test.go
- models/autoevent.go
- xrtmodels/schedule.go
The onChange flag in Device AutoEvent can prevent any non changed values sent out. The onChangeThreshold could provide the advanced feature, and the default value is 0, any changed value that exceeds (>) bounds shall be published. For example, Current_value - Current_prev > 0.01 shall be published where "Current_value" is the new value and "Current_prev" is the previously published value.
> feat: Add onChangeThreshold in Device AutoEvent

- dtos/reading.go
- dtos/requests/event_test.go
Since we accept the nil reading value, the binary reading value can be empty.
(cherry picked from commit d524d8c204f739d8b5b86ef1ba60ec8e5cd14733)
> fix: Allow binary reading value to be empty
