IOTechSystems/go-mod-core-contracts

- go.mod
All the custom changes before was targeting v1 models/client, not gonna pick them until a use case arises.
> EDX-1750 update import path

- go.mod
Reverts IOTechSystems/go-mod-core-contracts#46
> Revert "Bump github.com/google/uuid from 1.1.2 to 1.3.0"

- common/constants.go
- dtos/address.go
- dtos/address_test.go
- dtos/requests/subscription.go
- dtos/requests/subscription_test.go
- models/address.go
- models/intervalaction_test.go
- Add fields to MQTTPubAddress
- Add ZeroMQPubAddress
> EDX-1719 Pick the Notifications MQTT/0MQ enhancement from v1.8 to v2.0

- dtos/device.go
- models/device.go
> EDX-1865 add protocol field in Device model

- dtos/device.go
- models/device.go
- v1/models/action.go
- v1/models/command.go
- v1/models/describedobject.go
- v1/models/deviceprofile.go
- v1/models/deviceresource.go
- v1/models/errors.go
- v1/models/get.go
- v1/models/profileproperty.go
- v1/models/profileresource.go
- v1/models/propertyvalue.go
- v1/models/put.go
- v1/models/resourceoperation.go
- v1/models/response.go
- v1/models/timestamps.go
- v1/models/units.go
- v1/models/validator.go
- v1/transform.go
- v1/transform_test.go
- Add v1 DeviceProfile model
- Add func to transform the model between v1 and v2
> EDX-1847 Add v1 DeviceProfile model and transform func

- xrtmodels/deviceInfo.go
- xrtmodels/request.go
- xrtmodels/request_test.go
- xrtmodels/response.go
Move the xrtmodels from xrt-xpert-bridge to core-contracts.
> EDX-1937 Add XRT models

- common/constants.go
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/.github/Contributing.md.
EDX-1555
Add new constant to represent the service key for provision service
> EDX-1555 Implement the provision service to provision metadata service

- errors/types.go
> EDX-1955 add Unauthorized ErrKind

- dtos/deviceprofile.go
- dtos/deviceresource.go
- dtos/resourceoperation.go
- dtos/resourceproperties.go
> EDX-1995 Add YAML tag `omitempty` to the DTOs related to DeviceProfile

- v1models/transform.go
- v1models/transform_test.go
Convert StartingAddress attribute between 0-based and 1-based for Modbus device profile
> EDX-2001 Convert StartingAddress attribute between 0-based and 1-based

- dtos/deviceprofile.go
- dtos/deviceresource.go
- dtos/resourceoperation.go
- dtos/resourceproperties.go
- v1models/transform.go
- v1models/transform_test.go
> DCT-426 add json omitempty tag and deviceResource transform function

- dtos/deviceprofile.go
- v1models/transform.go
> DCT-426 remove validation on deviceResource

- common/tls.go
- Add Redis TLS function for creating the TLS config
- Add Redis TLS common constant
> EDX-1308 Add Redis TLS function

- clients/http/utils/common.go
Add ServiceUnavailable error checking to provide a more suitable error message
> EDX-2259 Add ServiceUnavailable Error

- dtos/deviceprofile_test.go
- dtos/deviceresource.go
- dtos/requests/deviceprofile_test.go
- models/deviceresource.go
> EDX-2416 add back 'Tag' field in DeviceResource

- clients/logger/logger.go
> EDX-2563 Update logger to use DefaultTimestamp for different timezone

- dtos/device.go
- dtos/requests/device.go
- dtos/requests/device_test.go
- models/device.go
[Issue link](https://iotechsys.atlassian.net/browse/EDX-2583)
Add Tags field to Device dto/model.
> EDX-2583 Add Tags field to Device dto/model

- common/validator.go
- xrtmodels/deviceInfo.go
- xrtmodels/request.go
- xrtmodels/request_test.go
- xrtmodels/response.go
- Update XRT models for v2
- Add colon char for XRT resource name
> EDX-2653 Update XRT models for v2

- xrtmodels/deviceInfo.go
- xrtmodels/request.go
- xrtmodels/response.go
- Add the protocolName when converting XRT model
- Update xrt request nad response json tag to match the latest changes
> EDX-2653 Add the protocolName when converting XRT model

- common/tls.go
> EDX-2690 Add constants for MQTT TLS

- common/validator.go
- xrtmodels/deviceInfo.go
- xrtmodels/request.go
- xrtmodels/request_test.go
- xrtmodels/response.go
Pick the changes from the XRT v2
> EDX-2653 Pick the changes from the XRT v2

- common/tls.go
> EDX-2690-4 Add constant BaseOutputDir

- dtos/provisionwatcher.go
> EDX-2780 Allow ProvisionWatcher to use empty profileName

- xrtmodels/request.go
- xrtmodels/request_test.go
Add options field for XRT resource put request, the options is optional for the specific protocol.
> EDX-2797 Add options field for XRT resource put request

- dtos/deviceprofile.go
- dtos/requests/deviceprofile.go
> fix: Remove DeviceProfileBasicInfo fieldName from validation error messages

- common/tls.go
Signed-off-by: Felix Ting [felix@iotechsys.com](mailto:felix@iotechsys.com)
> EDX-2805 Cherry pick the security enhancement commits to v2.2-branch

- go.sum
Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>
> EDX-2828 Upgrade gopkg.in/yaml.v3 to v3.0.0

- dtos/provisionwatcher.go
- dtos/provisionwatcher_test.go
- dtos/requests/provisionwatcher.go
- dtos/requests/provisionwatcher_test.go
- models/provisionwatcher.go
Add DeviceDescription to ProvisionWatcher for auto-discovered devices.
> EDX-2807 Add DeviceDescription to ProvisionWatcher

- common/constants.go
- common/utils.go
> DCT-608 Add ObjectArray to valueTypes for DCT

- common/constants.go
- models/user.go
> EDX-2846 add consts and user Model for proxy-auth JWT api

- dtos/deviceresource.go
- dtos/requests/deviceprofile_test.go
Remove resourceName unreserved chars checking to allow all characters.
> EDX-2921 Remove ResourceName unreserved chars checking

- xrtmodels/schedule.go
Add OnChange field to XRT Schedule, the OnChange field indicates that only changed values are published. Default value is false.
> EDX-2949 Add OnChange field to XRT Schedule

- .github/workflows/code-analysis.yml
- xrtmodels/schedule.go
The XRT's default value might be true, if we omit the false value in the JSON body, the Schedule result should be wrong.
> EDX-2949 Remove omitempty from XRT Schedule bool value

- common/dummy_validator.go
- common/validator.go
cherry-pick https://github.com/edgexfoundry/go-mod-core-contracts/commit/af18e4a16431a4442d66e7634db7cdbca34c2ef1
> build: add go build tag to exclude DTO validator

- dtos/notification.go
- dtos/notification_test.go
- dtos/requests/notification.go
- dtos/requests/notification_test.go
- models/notification.go
- Add new DTO `GetNotificationRequest`
- Add new field `Acknowledged` to Notification model
> PS-358 Update Notification DTO and model

- common/constants.go
> PS-366 Add /notification/ids/{ids} API route

- common/constants.go
> PS-367 Add API routes for notification ack status changes

- dtos/provisionwatcher.go
- dtos/provisionwatcher_test.go
- dtos/requests/provisionwatcher.go
- dtos/requests/provisionwatcher_test.go
- models/provisionwatcher.go
- xrtmodels/response.go
PW adds deviceNameTemplate, deviceLabels, profileNameTemplate, profileLabels, profileDescription fields.
> EDX-2968 Update provision watcher model and DTO

- dtos/deviceservice.go
- dtos/deviceservice_test.go
- dtos/requests/const_test.go
- dtos/requests/deviceservice.go
- dtos/requests/deviceservice_test.go
- models/deviceservice.go
> EDX-2996 Add transformScript to device service model and DTO

- clients/http/deviceservicecommand.go
- clients/http/deviceservicecommand_test.go
- clients/interfaces/deviceservicecommand.go
> EDX-3004 Add DS discovery client API

- common/constants.go
Add new constants for "tcps" protocol
Signed-off-by: Jude Hung <jude@iotechsys.com>
> EDX-3040 Enable MQTT TLS connection for Sparkplug

- xrtmodels/request.go
Add XRT DiscoveryRequest model and creation func
> EDX-3042 Add XRT DiscoveryRequest

- common/validator.go
- dtos/corecommand.go
- dtos/device.go
- dtos/devicecommand.go
- dtos/deviceprofilebasicinfo.go
- dtos/deviceresource.go
- dtos/event.go
- dtos/provisionwatcher.go
- dtos/reading.go
- dtos/requests/const_test.go
- dtos/requests/device_test.go
- dtos/requests/devicecommand.go
- dtos/requests/deviceprofile_test.go
- dtos/requests/deviceresource.go
- dtos/requests/event_test.go
- dtos/requests/provisionwatcher_test.go
> EDX-3024 Add ValidateDtoNoReservedChars for device/profile/resource/command

- xrtmodels/request.go
Add XRT ComponentUpdateRequest model
> EDX-3014 Add XRT ComponentUpdateRequest model

- .github/workflows/code-analysis.yml
Signed-off-by: jumpingliu <melody@iotechsys.com>
> EDX-3073 Remove the push trigger for go-mod-core-contract repo

- dtos/reading.go
- dtos/reading_test.go
Also pick https://github.com/IOTechSystems/go-mod-core-contracts/commit/11abf62a46295d843472fba39d0f82787a95ee5d from community
> EDX-3086 Remove SimpleReading value required validation for empty string 

- common/xpertconstants.go
- xrtmodels/deviceInfo.go
- xrtmodels/xrtconv.go
- xrtmodels/xrtconv_test.go
Add conversion func to convert the protocol properties between EdgeX model and XRT model
> EDX-3082 Add XRT properties conversion

- dtos/disconnectionnotificationcontent.go
> PS-344 Add DisconnectionNotificationContent DTO

- dtos/microservice.go
- dtos/responses/microservice.go
- dtos/responses/microservice_test.go
Add microservices DTOs from edgex-go-private sys-mgmt-agent.
Original DTOs locations from edgex-go-private:
- [dtos/microservice.go](https://github.com/IOTechSystems/edgex-go-private/blob/v2.2-branch/internal/system/agent/dtos/microservice.go#L36)
- [dtos/responses/microservice.go](https://github.com/IOTechSystems/edgex-go-private/blob/v2.2-branch/internal/system/agent/dtos/responses/microservice.go)
> EDX-3207 Add microservices DTOs for sys-mgmt

- common/constants.go
Add service key and API routes for new support-rulesengine service.
Signed-off-by: Jude Hung <jude@iotechsys.com>
> PS-390 Add support-rulesengine service key and API routes

- dtos/device.go
- dtos/deviceresource.go
- dtos/provisionwatcher.go
Remove the restriction from the device and resource name
> EDX-3305 Accept special characters in device and resource name

- CHANGELOG.md
- Makefile
- clients/http/utils/common.go
- common/constants.go
- dtos/device.go
- dtos/deviceservice.go
- dtos/metric.go
- dtos/reading.go
- dtos/responses/uom.go
- dtos/responses/uom_test.go
- dtos/systemevent.go
- dtos/systemevent_test.go
- go.mod
- models/device.go
- models/deviceservice.go
- v1models/transform.go
Signed-off-by: Felix Ting [felix@iotechsys.com](mailto:felix@iotechsys.com)
> EDX-3360 Upgrade go-mod-core-contracts to v2.3

- dtos/devicecommand.go
- dtos/event.go
- dtos/event_test.go
- dtos/reading.go
- dtos/reading_test.go
- models/devicecommand.go
- models/reading.go
> EDX-3401 Add Tags field to device command and reading data model

- xrtmodels/response.go
- xrtmodels/xrtconv.go
- Add sourceName and tags fields to XRT reading
- Add XRT to EdgeX Event conversion func
> PS-455 Add XRT to EdgeX Event conversion func

- common/tls.go
Add CreateRedisTlsConfigFromPEM common function.
> EDX-3605 Add CreateRedisTlsConfigFromPEM common function

- clients/doc.go
- clients/http/utils/common.go
- dtos/metric.go
- dtos/requests/devicecommand.go
- dtos/requests/deviceprofilebasicinfo.go
- dtos/requests/deviceresource.go
- go.mod
> EDX-3654 Upgrade go to 1.19 and fix lint errors

- common/constants.go
- dtos/devicechangednotification.go
- xrtmodels/devicestatus.go
Signed-off-by: Felix Ting [felix@iotechsys.com](mailto:felix@iotechsys.com)
> EDX-3583 Enrich DeviceNotificationContent

- dtos/event.go
- dtos/reading.go
- dtos/reading_test.go
- xrtmodels/xrtconv.go
Support object array reading DTO and model conversion
> EDX-3722 Support object array reading

- xrtmodels/request.go
- add AddDiscoveredDeviceRequest for adding device without profile
- add ScanDeviceRequest for discovering the profile
> EDX-3755 Update model for XRT v2.1

- clients/interfaces/xrt.go
- clients/messaging/xrt.go
- clients/messaging/xrtcomponent.go
- clients/messaging/xrtdevice.go
- clients/messaging/xrtdeviceprofile.go
- clients/messaging/xrtdiscovery.go
- clients/messaging/xrtschedule.go
- xrtmodels/request.go
Add XRT client func and accept discovery and status message handler
> EDX-3725 Add XRT client func

- common/constants.go
> EDX-3807 Add new service key for support-sparkplug-historian service

- dtos/responses/rule.go
- dtos/responses/rule_test.go
- dtos/rule.go
- dtos/rule_test.go
Signed-off-by: Felix Ting [felix@iotechsys.com](mailto:felix@iotechsys.com)
> EDX-3838 Add Rule DTO

- common/xpertconstants.go
- xrtmodels/xrtconv.go
- xrtmodels/xrtconv_test.go
Add conversion for new OPC-UA protocol properties ReadBatchSize, WriteBatchSize, NodesPerBrowse
> EDX-3993 Adds OPC-UA protocol properties conversion

- common/xpertconstants.go
- xrtmodels/xrtconv.go
- xrtmodels/xrtconv_test.go
Add conversion for new OPC-UA protocol properties SessionKeepAliveInterval.
> EDX-4018 Adds OPC-UA protocol properties conversion

- common/xpertconstants.go
- xrtmodels/xrtconv.go
- xrtmodels/xrtconv_test.go
Add conversion for new BACNet-IP protocol property port
> EDX-4061 Adds BACNet-IP protocol property conversion

- common/xpertconstants.go
Add EdgeNode constants for API path
> EDX-4111 Add EdgeNode constants

- common/edgecentral.go
Add resource value parsing function for specific value type
> EDX-4166 Add resource value parsing function

- common/xpertconstants.go
> EDX-4163 Add ContentTypeCSV constant

- common/xpertconstants.go
- xrtmodels/response.go
- xrtmodels/response_test.go
Convert EdgeX error to XRT error code.
> EDX-4113 Convert EdgeX error to XRT error code

- common/edgecentral.go
- common/edgecentral_test.go
- xrtmodels/xrtconv.go
Add Readings conversion function to convert from EdgeX to XRT format.
> EDX-4263 Add Readings conversion

- .github/dependabot.yml
> EDX-4261 Add golang.org/x/text dependabot

- common/xpertconstants.go
Add the service status error constants from sys-mgmt.
> EDX-4256 Add service status error constants

- Jenkinsfile
> EDX-4354 Use goModVersionTag in Jenkinsfile to bump tag version

- central/xlsx/device.go
- central/xlsx/device_test.go
- central/xlsx/interface.go
- central/xlsx/mapping.go
- central/xlsx/mapping_test.go
- central/xlsx/reader.go
- central/xlsx/reader_test.go
- central/xlsx/transform_test.go
- central/xlsx/utils.go
- central/xlsx/utils_test.go
- Add UTs for convert xlsx functions.
- Add error handlings for several functions.
> EDX-4328 Add UTs for convert xlsx functions

- central/dbc/transform.go
- central/dbc/transform_test.go
> PS-547-2 Refactor ConvertDBC funcs to accept []byte instead of io.Reader

- central/xlsx/constants.go
- central/xlsx/device.go
- central/xlsx/device_test.go
- central/xlsx/deviceprofile.go
- central/xlsx/deviceprofile_test.go
- central/xlsx/interface.go
- central/xlsx/mapping.go
- central/xlsx/mapping_test.go
- central/xlsx/reader.go
- central/xlsx/reader_test.go
- central/xlsx/transform.go
- central/xlsx/transform_test.go
- central/xlsx/utils.go
- central/xlsx/utils_test.go
Add parse excel to Device Profile DTO function.
> EDX-4329 Add parse excel to Device Profile DTO function

- central/xlsx/constants.go
- central/xlsx/device_test.go
- central/xlsx/reader.go
Support Tags definition in convert device xlsx.
> EDX-4397 Support Tags definition in convert device xlsx

- dtos/deviceprofile.go
- dtos/deviceprofile_test.go
Remove the limitation of binary write permission from profile checking.
> EDX-4455 Remove limitation of binary write permission

- central/xlsx/reader.go
> EDX-4457 Convert Attribute cell to bool or int types

- clients/http/device.go
- clients/interfaces/device.go
- common/constants.go
Add device update func with query parameter
> PS-579 Add device update func with query parameter

- common/xpertconstants.go
- xrtmodels/component.go
- xrtmodels/request.go
- xrtmodels/request_test.go
- xrtmodels/response.go
> EDX-4464 Add discover component API related xrt models

- xrtmodels/request.go
Add the missing Category field to NewComponentDiscoverRequest.
> EDX-4464 Add the missing Category field

- xrtmodels/deviceInfo.go
Add Tags field to ToEdgeXV2Device converted model.
> EDX-4534 Add Tags field to ToEdgeXV2Device

- central/xlsx/deviceprofile_test.go
- central/xlsx/reader.go
- central/xlsx/reader_test.go
Support xlsx Device Resource tags conversion.
> EDX-4551 Support xlsx Device Resource tags conversion

- central/xlsx/constants.go
- central/xlsx/reader.go
Add device xslx conversion to support all protocols.
> EDX-4635 Add device xslx conversion to support all prts

- central/xlsx/deviceprofile.go
- central/xlsx/deviceprofile_test.go
- central/xlsx/reader.go
Modify DeviceCommand sheet to vertical for xlsx conversion.
> EDX-4537 Modify DeviceCmd sheet to vertical for xlsx convert

- .github/workflows/code-analysis.yml
- Jenkinsfile
Replace goModVersionTag with repoVersionTag
> EDX-4717 Replace goModVersionTag with repoVersionTag

- central/xlsx/device.go
- central/xlsx/deviceprofile.go
- central/xlsx/transform_test.go
- central/xlsx/utils.go
- go.mod
- go.sum
Use slices from std library in 1.21 and fix test fail.
> EDX-4749 Use slices from std library in 1.21

- dtos/corecommand.go
- dtos/devicecommand.go
- dtos/deviceprofilebasicinfo.go
- dtos/deviceservice.go
- dtos/event_test.go
- dtos/provisionwatcher.go
- dtos/requests/const_test.go
- dtos/requests/deviceprofile_test.go
- dtos/requests/deviceservice_test.go
- dtos/requests/provisionwatcher_test.go
Remove the DTO name restriction as community changes, https://github.com/edgexfoundry/go-mod-core-contracts/pull/853.
> EDX-4765 Remove the DTO name restriction

- common/constants.go
> EDX-4772 Update sys-mgmt-agent svc key to sys-mgmt

- common/xpertconstants.go
- xrtmodels/xrtconv.go
- xrtmodels/xrtconv_test.go
Add EtherCAT properties conversion.
> EDX-4805 Add EtherCAT properties conversion

- common/xpertconstants.go
Update EtherCAT protocol to upper camel case.
> EDX-4805 Update EtherCAT protocol name

- Jenkinsfile
Replace goModVersionTag with repoVersionTag, update v2.3-branch
> EDX-4808(2.3) Replace goModVersionTag with repoVersionTag

- xrtmodels/component.go
- xrtmodels/request.go
- xrtmodels/response.go
Add XRT components discovery model and constants.
> PS-628 Add XRT components discovery model

- xrtmodels/constants.go
- xrtmodels/response.go
Update XRT ComponentsDiscoveryResponse model and add XRT MQTT message type constants.
> PS-628 Update XRT ComponentsDiscovery model

- central/xlsx/deviceprofile_test.go
- central/xlsx/reader.go
- central/xlsx/reader_test.go
Support device resource nested attribute value xlsx conversion.
> EDX-4799 Support nested attribute xlsx conversion

- xrtmodels/deviceInfo.go
- xrtmodels/request.go
- xrtmodels/request_test.go
- xrtmodels/xrtconv_test.go
Update xrt model to use device and device profile DTO.
> PS-628 Update xrt model

- central/xlsx/device_test.go
- central/xlsx/reader.go
- central/xlsx/reader_test.go
- central/xlsx/utils.go
- central/xlsx/utils_test.go
- Convert the fields into Device Properties map
- Convert the Properties/Tags/ProtocolProperties values into actual type
> EDX-4887 Apply with v3 Device DTO change for xlsx conversion

- common/central.go
- xrtmodels/constants.go
- xrtmodels/notification.go
> EDX-4909 Add XRT notification model

- common/central_constants.go
- xrtmodels/schedule.go
> EDX-4710 Add BACnet COV properties

- xrtmodels/deviceInfo.go
- xrtmodels/deviceinfo_test.go
Fix xrt model conversion nil pointer error
> EDX-4964 Fix xrt model conversion nil pointer error

- central/xlsx/constants.go
- central/xlsx/device_test.go
- central/xlsx/dpXlsxWriter.go
- central/xlsx/dpXlsxWriter_test.go
- central/xlsx/reader_test.go
- central/xlsx/transform.go
- central/xlsx/transform_test.go
Add convert device profile to xlsx feature based on the passed xlsx template file reader.
> EDX-4993 Add convert device profile to xlsx feature

- central/xlsx/dpXlsxWriter.go
- central/xlsx/dpXlsxWriter_test.go
- central/xlsx/transform_test.go
> EDX-4993 Handle convert nested resource attributes to xlsx

- central/xlsx/constants.go
- central/xlsx/device_test.go
- central/xlsx/devicesXlsxWriter.go
- central/xlsx/devicesXlsxWriter_test.go
- central/xlsx/dpXlsxWriter.go
- central/xlsx/dpXlsxWriter_test.go
- central/xlsx/interface.go
- central/xlsx/transform.go
- central/xlsx/transform_test.go
> EDX-5009 Support convert Device DTO to xlsx file

- dtos/device.go
- dtos/requests/device_test.go
> feat: Remove the restrition of Device Protocols

- xrtmodels/component.go
Add MiddlewareTopicPrefix const for OPC-UA Server and middleware service integration.
> EDX-5014 Add MiddlewareTopicPrefix const

- dtos/device.go
- dtos/requests/device_test.go
> feat: Allow empty profileName in Device

- common/constants.go
- dtos/deviceprofile.go
- dtos/deviceprofile_test.go
- dtos/responses/deviceprofile.go
- dtos/responses/deviceprofile_test.go
Add multiple profile basic info DTO for /api/v3/deviceprofile/basicinfo/all API
> feat: Add multiple profile basic info DTO

- clients/http/utils/request.go
> Check the response content length before invoking json.Unmarshal 

- Makefile
- go.mod
Upgrade to go-1.23, Linter1.61.0
> build: Upgrade to go-1.23, Linter1.61.0

- dtos/reading.go
- dtos/reading_test.go
- dtos/requests/event_test.go
- models/reading.go
Allow store reading value as null.
> feat: Allow store reading value as null

- dtos/event.go
- dtos/event_test.go
- dtos/reading.go
- dtos/reading_test.go
- dtos/requests/event.go
- dtos/requests/event_test.go
- models/reading.go
- xrtmodels/xrtconv.go
[EDX-5329: cherry-pick community changes](https://github.com/IOTechSystems/go-mod-core-contracts/commit/cf2d24b888068074a50b434e0f67cb0351b5cd00)
> EDX-5329 Pick changes for nil reaing refactor

- dtos/requests/user.go
- dtos/requests/user_test.go
- dtos/responses/token.go
- dtos/responses/token_test.go
- dtos/user.go
- models/token.go
- models/user.go
Add token dto/model.
Add DisplayName field in User dto.
> EDX-5341 Add token dto/model

- dtos/requests/rolepolicy.go
- dtos/requests/rolepolicy_test.go
- dtos/responses/rolepolicy.go
- dtos/responses/rolepolicy_test.go
- dtos/rolepolicy.go
- dtos/rolepolicy_test.go
- models/rolepolicy.go
Add role policy related dtos/models.
> EDX-5339 Add role policy dtos/models

- dtos/requests/rolepolicy_test.go
- dtos/rolepolicy.go
- models/token.go
> EDX-5339 RolePolicy DTO and TokenDetails model updated

- xrtmodels/component.go
Add XRT EdgeXCompat constant for discovery request
> EDX-5513 Add XRT EdgeXCompat constant
